[settings.github]
github_attestations = false

[tools]
erlang = "latest"
elixir = "latest"
node = "latest"
python = "latest"
neovim = "latest"
tree-sitter = "latest"
bun = "latest"
"ubi:elixir-lang/expert" = "nightly"
"aqua:anthropics/claude-code" = "latest"
"github:cli/cli" = "latest"
"aqua:ankitpokhrel/jira-cli" = "latest"
awscli = "latest"
